blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/minhlucvan/notebookmd/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
